### ISSUE TITLE
Termin 11.06.2018

### ISSUE THREAD

**Issue by Yucel-Polat** [THK-ADV/java-tutorial-current#11]
Findet heute das Tutorium statt? 
Wenn ja welche Themen haben wir?

Vielen dank .

**Comment by fleonhard** [comment]
Ja das Tutorium findet statt allerdings sind die Themen noch nicht bekannt. Hast du einen speziellen Wunsch?

**Comment by Yucel-Polat** [comment]
Wäre es möglich Doppelt verkettete listen  zu bearbeiten .?

**Comment by Yucel-Polat** [comment]
Liebe Grüße

**Comment by fleonhard** [comment]
Nein, wenn du speziell Fragen hast können wir diese Klären jedoch werden wir nicht die Lösung für das Praktikum generieren.

**Comment by Yucel-Polat** [comment]
Okay Danke

**Comment by gilo2754** [comment]
Hallo.
Allerdings ist Doppelt verkettete Listen ein Thema die viele noch nicht ganz verstehen(ich mindesten).
Ich würde nicht bitten, dass die Aufgaben der Praktika gelöst werden. 
Wenn wir aber das Thema allgemein behandeln könnten, würde ganz hilfreich finden.
Grüße!
