### ISSUE TITLE
Java Class Calendar

### ISSUE THREAD

**Issue by klixt** [THK-ADV/java-tutorial-current#9]
Hallo zusammen,
Ich habe folgendes Problem: im ersten Praktikum  hatten wir in der Klasse Trainingseinheit ein Datum und eine Trainingszeit zu definieren. Der Betreuer, bei dem ich abgegeben habe , meinte, das sollte mit der Klasse Calendar gemacht werden.   Wie benutzt man überhaupt sinnvoll diese Klasse in so einem Fall?

public class Trainingseinheit {
    private int trainingsdauer;
    private String startzeit;   //TODO: mit java.util.calendar machen!
    private String trainingsdatum; //TODO: mit java.util.calendar machen!
    private Fitnessgeraet fitnessgeraet;

    public Trainingseinheit(Fitnessgeraet fitnessgeraet, String startzeit, String trainingsdatum ) {
        this.fitnessgeraet = fitnessgeraet;
        this.startzeit = startzeit;
        this.trainingsdatum = trainingsdatum;

    }

Zudem sollen wir jetzt eine Subclass  der Klasse Trainingseinheit schreiben , die ähnliche Eigenschaften besitzt , wie die Oberklasse. Hat das vielleicht auch was mit dem Kalendar zu tun?

<img width="525" alt="ap2" src="https://user-images.githubusercontent.com/38865689/40061724-e230c536-5859-11e8-812f-3d98f1b937fa.PNG">

Danke im Voraus!

**Comment by fleonhard** [comment]
Um zu verstehen wie `Calendar` funktioniert bringt google ein paar nützliche Seiten hervor. Dort sind ziemlich hilfreiche Tutorials und Beschreibungen zu finden wie zum Beispiel:

[http://openbook.rheinwerk-verlag.de/javainsel9/javainsel_15_006.htm](http://openbook.rheinwerk-verlag.de/javainsel9/javainsel_15_006.htm)
oder
[https://www.mkyong.com/java/java-date-and-calendar-examples/](https://www.mkyong.com/java/java-date-and-calendar-examples/)

Zudem gibt es zu jeder von Java gelieferten Klasse eine Dokumentation. Diese Dokus sind zwar etwas ungewohnt zu lesen, jedoch ist es erstens gut früh genug zu lernen mit diesen Dokus umzugehen und zweitens sind dort eigentlich alle Informationen die man benötigt um diese Klasse zu nutzen. Die Doku zu `Calendar` findest du unter 
[https://docs.oracle.com/javase/7/docs/api/java/util/Calendar.html](https://docs.oracle.com/javase/7/docs/api/java/util/Calendar.html)

Alternativ kannst du diese Aufgabe auch mit `Date`, `LocalDate`, `LocalDateTime` oder anderen Klassen lösen, falls dir das leichter Fällt. Nur einen String solltest du dafür nicht verwenden, da man mit diesem String nur schwer weiterarbeiten kann. Die eben genannten Klassen bieten dir einige Funktionen, die dir bei dem Umgang mit einem Datum helfen.

Guck dir diese Seiten mal an, und versuch es dann nochmal. Falls du noch Fragen hast, kannst du sie gerne stellen. Dazu schreibst du am besten einen Kommentar unter dieses Issue. Gerade in dem zweiten Link sind einige Anwendungsbeispiele und soweit ich sehen konnte alle Informationen, die du benötigst.

Die Implementierung des Interface hat erst einmal nichts mit `Calendar` zu tun. Alles was du dazu benötigst haben wir im letzten Tutorial besprochen. Dazu guck dir am besten noch einmal den Code aus dem letzten Termin an. Im Ordner Exkurs findest du auch die Beispiele dazu im Bereich _abstraktion_.

Die Konstruktoren der Oberklasse kannst du mit `super(<parameter>)` und Konstruktoren der eigenen Klasse über `this(<parameter>)` aufrufen.

Ich hoffe ich konnte dir auf die Schnelle helfen.

**Comment by klixt** [comment]
Hallo Florian ,herzlichen Dank für die  schnelle und  ausführliche Antwort. Hilfreich ist das ganze auf jeden fall. damit arbeite ich jetzt weiter , bis ich noch Probleme habe.
Grüße


    Le ‎mardi‎ ‎15‎ ‎mai‎ ‎2018‎ ‎19‎:‎54‎:‎37‎ ‎CEST, Florian Herborn <notifications@github.com> a écrit :  
 
 
Um zu verstehen wie Calendar funktioniert bringt google ein paar nützliche Seiten hervor. Dort sind ziemlich hilfreiche Tutorials und Beschreibungen zu finden wie zum Beispiel:

http://openbook.rheinwerk-verlag.de/javainsel9/javainsel_15_006.htm
oder
https://www.mkyong.com/java/java-date-and-calendar-examples/

Zudem gibt es zu jeder von Java gelieferten Klasse eine Dokumentation. Diese Dokus sind zwar etwas ungewohnt zu lesen, jedoch ist es erstens gut früh genug zu lernen mit diesen Dokus umzugehen und zweitens sind dort eigentlich alle Informationen die man benötigt um diese Klasse zu nutzen. Die Doku zu Calendar findest du unter
https://docs.oracle.com/javase/7/docs/api/java/util/Calendar.html

Alternativ kannst du diese Aufgabe auch mit Date, LocalDate, LocalDateTime oder anderen Klassen lösen, falls dir das leichter Fällt. Nur einen String solltest du dafür nicht verwenden, da man mit diesem String nur schwer weiterarbeiten kann. Die eben genannten Klassen bieten dir einige Funktionen, die dir bei dem Umgang mit einem Datum helfen.

Guck dir diese Seiten mal an, und versuch es dann nochmal. Falls du noch Fragen hast, kannst du sie gerne stellen. Dazu schreibst du am besten einen Kommentar unter dieses Issue. Gerade in dem zweiten Link sind einige Anwendungsbeispiele und soweit ich sehen konnte alle Informationen, die du benötigst.

Die Implementierung des Interface hat erst einmal nichts mit Calendar zu tun. Alles was du dazu benötigst haben wir im letzten Tutorial besprochen. Dazu guck dir am besten noch einmal den Code aus dem letzten Termin an. Im Ordner Exkurs findest du auch die Beispiele dazu im Bereich abstraktion.

Die Konstruktoren der Oberklasse kannst du mit super(<parameter>) und Konstruktoren der eigenen Klasse über this(<parameter>) aufrufen.

Ich hoffe ich konnte dir auf die Schnelle helfen.

**Comment by fleonhard** [comment]
Ich habe soeben ein paar Beispiele zu den Klassen `LocalDateTime`, `Date` und `Calendar` hinzugefügt. Dort kannst du dir einmal angucken, wie man mit diesen verschiedenen Klassen arbeiten kann. Jetzt musst du dir nur noch eine aussuchen und nutzen. 

`Date` ist _deprecated_, was soviel bedeutet, dass `Date` veraltet ist und nichtmehr verwendet werden sollte (man kann es natürlich verwenden, jedoch empfiehlt Oracle, stattdessen `Calendar` zu nutzen).

Zu finden sind die Beispiele [hier](https://github.com/THK-ADV/java-tutorial-current/tree/master/Beispiele/src/beispiele/dates).
